services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      cafedra_bots:
        ipv4_address: 10.5.0.5
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  runc:
    container_name: runc
    build:
      context: ./src/
    restart: always

    ports:
      - "${PORT}:8080"
    env_file: .env
    networks:
      cafedra_bots:
        ipv4_address: 10.5.0.26





networks:
  cafedra_bots:
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/25
